import {normalizeHandle,validateSelection,selectionKey,filterProblems,validRatingRange,recommendationPool,recommend} from '/domain.js';
// Keep the established storage keys so the new identity preserves saved comparisons.
const $=id=>document.getElementById(id), KEY='practice-queue.settings.v2', DATA='practice-queue.result.v2', PAGE=25;
const defaults={learner:'donaldgera',sources:['catgirl'],mode:'any',randomMin:'0',randomMax:'1600',showRatings:true,showTags:false,tab:'queue',filters:{queue:{},completed:{}}};
let settings=structuredClone(defaults),result=null,busy=false,controller=null,page=0,picked=null,lastAttempt=0,lastForce=false,storageWarning=false;
try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved&&typeof saved==='object'){settings={...defaults,learner:typeof saved.learner==='string'?saved.learner:defaults.learner,sources:Array.isArray(saved.sources)?saved.sources.filter(h=>typeof h==='string').slice(0,5):defaults.sources,mode:saved.mode==='all'?'all':'any',randomMin:String(saved.randomMin??defaults.randomMin),randomMax:String(saved.randomMax??defaults.randomMax),showRatings:saved.showRatings!==false,showTags:saved.showTags===true,tab:saved.tab==='completed'?'completed':'queue',filters:{queue:saved.filters?.queue||{},completed:saved.filters?.completed||{}}};}}catch{/* An unavailable preference store uses the defaults. */}
try{const cached=JSON.parse(localStorage.getItem(DATA));if(cached?.schemaVersion===2&&Array.isArray(cached.queue)&&Array.isArray(cached.completed)){validateSelection(cached.selection);result=cached;}}catch{/* Keep preference restoration independent from the last complete result. */}
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number(n).toLocaleString();
const date=value=>new Date(value).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'});
const dateTime=value=>new Date(value).toLocaleString(undefined,{year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
const link=(url,label,cls='')=>`<a class="${cls}" href="${escape(url)}" target="_blank" rel="noopener noreferrer">${escape(label)}</a>`;
function note(message){$('cache-note').textContent=message;$('cache-note').hidden=!message;}
function save(){try{localStorage.setItem(KEY,JSON.stringify(settings));}catch{storageWarning=true;note('Browser storage is unavailable. Your selection works here but may not be remembered when you leave.');}}
function selection(){return validateSelection({learner:$('learner').value,sources:settings.sources,mode:document.querySelector('[name=mode]:checked').value});}
function changed(){settings.learner=$('learner').value;settings.mode=document.querySelector('[name=mode]:checked').value;save();let differs=true;try{differs=result&&selectionKey(selection())!==selectionKey(result.selection);}catch{}$('selection-changed').hidden=!result||!differs;}
function renderChips(){$('source-count').textContent=`${settings.sources.length} / 5`;$('source-chips').innerHTML=settings.sources.map((h,i)=>`<span class="chip"><span>${escape(h)}</span><button type="button" data-remove="${i}" aria-label="Remove ${escape(h)}">×</button></span>`).join('');}
function sourceError(message=''){$('source-error').textContent=message;$('source-error').hidden=!message;$('source-input').setAttribute('aria-invalid',String(!!message));}
function addSource(){try{const h=normalizeHandle($('source-input').value);if(settings.sources.length>=5)throw new Error('You can compare up to five sources. Remove one to add another.');if(settings.sources.some(x=>x.toLowerCase()===h.toLowerCase()))throw new Error('This source is already selected.');if(h.toLowerCase()===$('learner').value.trim().toLowerCase())throw new Error('Choose a different source from your own handle.');settings.sources.push(h);$('source-input').value='';sourceError();renderChips();changed();return true;}catch(e){sourceError(e.message);return false;}}
function error(message,title='Couldn’t refresh'){$('error-title').textContent=title;$('error-message').textContent=message;$('error').hidden=false;}
function applySelection(){ $('learner').value=settings.learner;document.querySelector(`[name=mode][value=${settings.mode==='all'?'all':'any'}]`).checked=true;renderChips(); }
function filterState(){return settings.filters[settings.tab]||{};}
function loadFilters(){const f=filterState();for(const [id,key]of [['search','search'],['min-rating','min'],['max-rating','max'],['tag','tag'],['sort','sort']])$(id).value=f[key]??(key==='sort'?'oldest':'');}
function readFilters(){return {search:$('search').value,min:$('min-rating').value===''?null:Number($('min-rating').value),max:$('max-rating').value===''?null:Number($('max-rating').value),tag:$('tag').value,sort:$('sort').value};}
function rating(p){return `<span class="rating${p.rating===null?' unrated':''}">${p.rating===null?'Unrated':fmt(p.rating)}</span>`;}
function solutionLinks(p){return p.solvedBy.map(s=>link(s.submissionUrl,`${s.handle} · accepted`,'solution-link')).join('');}
function renderList(){if(!result)return;const completed=settings.tab==='completed',all=result[settings.tab],f=readFilters();
  const invalid=(f.min!==null&&(!Number.isInteger(f.min)||f.min<0))||(f.max!==null&&(!Number.isInteger(f.max)||f.max<0))||(f.min!==null&&f.max!==null&&f.min>f.max);
  const filtered=invalid?[]:filterProblems(all,f);page=Math.min(page,Math.max(0,Math.ceil(filtered.length/PAGE)-1));const start=page*PAGE,shown=filtered.slice(start,start+PAGE);
  $('filter-summary').textContent=invalid?'Enter valid rating limits; minimum must be at or below maximum.':`${fmt(filtered.length)} of ${fmt(all.length)} problems${f.min!==null||f.max!==null?' · unrated excluded':''}`;
  $('date-heading').textContent=completed?'Your first solve':'First source solve';
  $('problem-rows').innerHTML=shown.map((p,i)=>`<tr><td class="number-cell">${fmt(start+i+1)}</td><td><a class="problem-title" href="${escape(p.url)}" target="_blank" rel="noopener noreferrer"><span class="problem-id">${escape(p.id)}</span>${escape(p.title)}</a><div class="problem-links">${solutionLinks(p)}${completed?link(p.learnerSubmissionUrl,'Your accepted solution','solution-link'):''}</div>${settings.showTags&&p.tags.length?`<div class="problem-tags">${p.tags.map(escape).join(' · ')}</div>`:''}</td>${settings.showRatings?`<td>${rating(p)}</td>`:''}<td class="date-cell"><time title="${escape(dateTime(completed?p.learnerSolvedAt:p.firstSolvedAt))}">${escape(date(completed?p.learnerSolvedAt:p.firstSolvedAt))}</time><small>${completed?`Source: ${escape(date(p.firstSolvedAt))}`:escape(p.sourceHandle)}</small></td></tr>`).join('');
  $('empty').hidden=!!filtered.length;$('empty-title').textContent=invalid?'Check your rating range':all.length?'No matching problems':completed?'No shared solves yet':'You’re all caught up';$('empty-message').textContent=invalid?'Use whole, non-negative ratings and keep minimum below maximum.':all.length?'Try a different rating range, topic, or search.':completed?'Problems you and the selected sources have both solved will appear here.':'There are no unsolved problems for this selection. Try adding sources or using Any source.';
  $('page-summary').textContent=filtered.length?`${fmt(start+1)}–${fmt(start+shown.length)} of ${fmt(filtered.length)}`:'0 problems';$('previous').disabled=page===0;$('next').disabled=start+PAGE>=filtered.length;
  for(const tab of ['queue','completed']){$(`${tab}-tab`).setAttribute('aria-selected',String(tab===settings.tab));$(`${tab}-tab`).tabIndex=tab===settings.tab?0:-1;}
  $('problem-list').setAttribute('aria-labelledby',`${settings.tab}-tab`);
}
function randomRange(){return {min:$('random-min').value===''?NaN:Number($('random-min').value),max:$('random-max').value===''?NaN:Number($('random-max').value)};}
function renderRandom(){const {min,max}=randomRange(),valid=validRatingRange(min,max),eligible=recommendationPool(result?.queue||[],min,max),count=eligible.length;
  $('random-min').setAttribute('aria-invalid',String(!valid));$('random-max').setAttribute('aria-invalid',String(!valid));
  $('pick').disabled=!valid||!count;$('random-count').textContent=!valid?'Enter both ratings as non-negative whole numbers. Minimum must be at or below maximum.':!result?'Build a queue to start.':count?`${fmt(count)} eligible problem${count===1?'':'s'}${count===1?' · this is the only match':''}.`:`No problems are rated between ${fmt(min)} and ${fmt(max)}. Try a different range.`;
  if(picked&&!eligible.some(p=>p.key===picked.key))picked=null;
  $('recommendation').innerHTML=picked?`<div class="recommendation">${link(picked.url,`${picked.id} · ${picked.title}`)}<p>${settings.showRatings?`<span class="recommendation-rating">Rating ${fmt(picked.rating)} · </span>`:''}${escape(date(picked.firstSolvedAt))}</p>${link(picked.firstSubmissionUrl,`${picked.sourceHandle}’s accepted solution`,'solution-link')}</div>`:'';$('pick').textContent=picked?'Pick another':'Pick a problem';
}
function applyRatingVisibility(){$('show-ratings').checked=settings.showRatings;$('rating-heading').hidden=!settings.showRatings;renderList();renderRandom();}
function renderResult(){if(!result)return;$('welcome').hidden=true;$('results').hidden=false;$('results-title').textContent=`${result.selection.learner}’s queue`;$('selection-badge').textContent=result.selection.mode==='all'?'All sources':'Any source';
  for(const [id,key]of [['stat-queue','queue'],['stat-completed','completed'],['stat-sources','sourceTotal'],['stat-learner','learnerSolved']])$(id).textContent=fmt(result.stats[key]);
  $('queue-tab-count').textContent=fmt(result.queue.length);$('completed-tab-count').textContent=fmt(result.completed.length);
  $('source-stats').innerHTML=result.sourceStats.map(s=>`<span class="source-stat">${link(`https://codeforces.com/profile/${encodeURIComponent(s.handle)}`,s.handle)} · ${fmt(s.solved)} solved · ${fmt(s.shared)} shared</span>`).join('');
  $('refresh-time').textContent=dateTime(result.lastSuccessfulRefresh);$('refresh-time').dateTime=result.lastSuccessfulRefresh;$('refresh-time').title='Oldest history in this comparison';
  const tags=[...new Set([...result.queue,...result.completed].flatMap(p=>p.tags))].sort();$('tag').innerHTML='<option value="">All topics</option>'+tags.map(t=>`<option value="${escape(t)}">${escape(t)}</option>`).join('');loadFilters();renderList();renderRandom();changed();
}
async function run(force=false){if(busy)return;if($('source-input').value.trim()&&!addSource())return;let chosen;try{chosen=selection();}catch(e){error(e.message,'Check your handles');return;}
  busy=true;lastForce=force;lastAttempt=Date.now();controller=new AbortController();$('selection-fields').disabled=true;$('refresh').disabled=true;$('error').hidden=true;$('progress-panel').hidden=false;$('progress').value=0;$('progress-message').textContent='Checking Codeforces handles…';note('');
  try{const response=await fetch('/api/compare',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...chosen,force}),signal:controller.signal});if(!response.ok){const failure=await response.json();throw new Error(failure.error||`Refresh failed (HTTP ${response.status}).`);}const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='',received=null;
    const consume=line=>{if(!line.trim())return;const event=JSON.parse(line);if(event.type==='error')throw new Error(event.error);if(event.type==='progress'){$('progress-message').textContent=event.message;$('progress').value=Math.min(100,event.completed/event.total*100);}if(event.type==='result')received=event.data;};
    while(true){const {value,done}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});let end;while((end=buffer.indexOf('\n'))>=0){consume(buffer.slice(0,end));buffer=buffer.slice(end+1);}if(done)break;}consume(buffer);if(!received)throw new Error('The connection ended before a complete comparison arrived. Please retry.');
    result=received;settings={...settings,...result.selection};picked=null;page=0;applySelection();save();try{localStorage.setItem(DATA,JSON.stringify(result));}catch{storageWarning=true;}renderResult();note(storageWarning?'Results updated. Your browser could not save the complete comparison for your next visit.':force?'Refreshed just now.':'Queue ready.');
  }catch(e){if(e.name==='AbortError')note('Refresh cancelled. Your last complete comparison is still available.');else error(`${e.message}${result?' Your previous results and settings are preserved.':''}`);}
  finally{busy=false;controller=null;$('selection-fields').disabled=false;$('refresh').disabled=false;$('progress-panel').hidden=true;}
}
$('selection-form').addEventListener('submit',e=>{e.preventDefault();run(false);});$('add-source').addEventListener('click',addSource);$('source-input').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();addSource();}});$('source-chips').addEventListener('click',e=>{const b=e.target.closest('[data-remove]');if(b){settings.sources.splice(Number(b.dataset.remove),1);renderChips();changed();}});$('learner').addEventListener('input',changed);document.querySelectorAll('[name=mode]').forEach(el=>el.addEventListener('change',changed));$('refresh').addEventListener('click',()=>run(true));$('retry').addEventListener('click',()=>run(lastForce));$('cancel').addEventListener('click',()=>controller?.abort());
for(const id of ['search','min-rating','max-rating','tag','sort'])$(id).addEventListener(id==='tag'||id==='sort'?'change':'input',()=>{settings.filters[settings.tab]=readFilters();page=0;save();renderList();});
function setTab(tab){settings.tab=tab;page=0;loadFilters();save();renderList();}
document.querySelectorAll('[data-tab]').forEach(el=>{el.addEventListener('click',()=>setTab(el.dataset.tab));el.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const tab=e.key==='Home'?'queue':e.key==='End'?'completed':settings.tab==='queue'?'completed':'queue';setTab(tab);$(`${tab}-tab`).focus();}});});
$('clear-filters').addEventListener('click',()=>{settings.filters[settings.tab]={};page=0;save();loadFilters();renderList();});$('previous').addEventListener('click',()=>{page--;renderList();});$('next').addEventListener('click',()=>{page++;renderList();});for(const id of ['random-min','random-max'])$(id).addEventListener('input',()=>{settings.randomMin=$('random-min').value;settings.randomMax=$('random-max').value;picked=null;save();renderRandom();});$('pick').addEventListener('click',()=>{const {min,max}=randomRange();picked=recommend(result.queue,min,max,picked?.key);renderRandom();});$('show-ratings').addEventListener('change',()=>{settings.showRatings=$('show-ratings').checked;save();applyRatingVisibility();});$('show-tags').addEventListener('change',()=>{settings.showTags=$('show-tags').checked;save();renderList();});
async function autoRefresh(){if(!busy&&result&&!$('source-input').value.trim()&&document.visibilityState==='visible'&&Date.now()-lastAttempt>15*60*1000&&Date.now()-Date.parse(result.lastSuccessfulRefresh)>=86400000){try{if(selectionKey(selection())===selectionKey(result.selection))await run(true);}catch{}}}
if(!['queue','completed'].includes(settings.tab))settings.tab='queue';$('show-tags').checked=settings.showTags;applySelection();$('random-min').value=settings.randomMin;$('random-max').value=settings.randomMax;renderResult();applyRatingVisibility();if(result)note('Saved comparison. Refresh for the latest solves.');autoRefresh();document.addEventListener('visibilitychange',autoRefresh);setInterval(autoRefresh,15*60*1000);
if(navigator.modelContext?.registerTool){for(const tool of [{name:'generate_practice_queue',description:'Generate the comparison for the handles currently selected in the form.',inputSchema:{type:'object',properties:{}},execute:async()=>{await run(false);return{content:[{type:'text',text:JSON.stringify(result?.stats||{error:$('error-message').textContent})}]};}},{name:'refresh_practice_queue',description:'Fetch fresh Codeforces histories for the currently selected handles.',inputSchema:{type:'object',properties:{}},execute:async()=>{await run(true);return{content:[{type:'text',text:JSON.stringify(result?.stats||{error:$('error-message').textContent})}]};}}]){try{navigator.modelContext.registerTool(tool);}catch{}}}
